spring.application.name=DiscordBotDevelopment
server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

discord.bot.token=${DISCORD_BOT_TOKEN}
discord.default-channel-id=${DISCORD_CHANNEL_ID}
discord.github-feed-channel-id=${DISCORD_GITHUB_FEED_CHANNEL_ID:${DISCORD_CHANNEL_ID}}
discord.pr-status-channel-id=${DISCORD_PR_STATUS_CHANNEL_ID}
discord.bot-alerts-channel-id=${DISCORD_BOT_ALERTS_CHANNEL_ID}
